package es.upm.dia.oeg.lld.search.utils;

public class AppConstants {

    public static final String HOST = "localhost";
    public static final int CLIENT_PORT = 9300;
    public static final String INDEX = "lldsearch";
    public static final String DIRECTTRANS_TYPE = "directTrans";
    public static final String SPARQL_ENDPOINT = "http://linguistic.linkeddata.es/sparql/";

    // **************** SPARQL queries *******************
    public static final String GET_ALL_LANGUAGES_QUERY = "PREFIX lemon: <http://www.lemon-model.net/lemon#> "
            + "PREFIX tr: <http://purl.org/net/translation#> "
            + "PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#> "
            + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
            + "SELECT distinct ?lexicon_a ?lang "
            + "WHERE {"
            + "  ?lexicon_a a lemon:Lexicon ; "
            + "    lemon:language ?lang ; "
            + "    rdfs:label ?label . " + "} ORDER BY ?lang ";

    public static final String GET_DIRECT_TRANSLATIONS_ALL_LANGUAGES_BABELNET = "PREFIX lemon: <http://www.lemon-model.net/lemon#> "
            + "PREFIX tr: <http://purl.org/net/translation#> "
            + "PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#> "
            + "SELECT DISTINCT ?written_rep_target ?POS ?lexicon_source ?lexicon_target ?babelnet "
            + "WHERE { "
            + "?form_source lemon:writtenRep %s . "
            + "?lex_entry_source lemon:lexicalForm ?form_source . "
            + "?sense_source lemon:isSenseOf  ?lex_entry_source .  "
            + "?lexicon_source lemon:entry ?lex_entry_source . "
            + "?lexicon_source lemon:language %s .  "
            + "?trans  tr:translationSense  ?sense_source .  "
            + "?trans  tr:translationSense  ?sense_target .  "
            + "?sense_target lemon:isSenseOf  ?lex_entry_target .   "
            + "?lex_entry_target lemon:lexicalForm ?form_target . "
            + "?form_target lemon:writtenRep ?written_rep_target . "
            + "?lex_entry_target  lexinfo:partOfSpeech ?POS .   "
            + "?lexicon_target lemon:entry ?lex_entry_target . "
            + "minus { ?lexicon_target lemon:language %s } "
            + "optional {?sense_source lemon:reference ?babelnet "
            + "}} ORDER BY ?lexicon_target ";

    public static final String GET_DIRECT_TRANSLATIONS_ALL_LANGUAGES = "PREFIX lemon: <http://www.lemon-model.net/lemon#> "
            + "PREFIX tr: <http://purl.org/net/translation#> "
            + "PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#> "
            + "SELECT DISTINCT ?written_rep_target ?POS ?lexicon_source ?lexicon_target "
            + "WHERE { "
            + "?form_source lemon:writtenRep %s . "
            + "?lex_entry_source lemon:lexicalForm ?form_source . "
            + "?sense_source lemon:isSenseOf  ?lex_entry_source .  "
            + "?lexicon_source lemon:entry ?lex_entry_source . "
            + "?lexicon_source lemon:language %s .  "
            + "?trans  tr:translationSense  ?sense_source .  "
            + "?trans  tr:translationSense  ?sense_target .  "
            + "?sense_target lemon:isSenseOf  ?lex_entry_target .   "
            + "?lex_entry_target lemon:lexicalForm ?form_target . "
            + "?form_target lemon:writtenRep ?written_rep_target . "
            + "?lex_entry_target  lexinfo:partOfSpeech ?POS .   "
            + "?lexicon_target lemon:entry ?lex_entry_target . "
            + "minus { ?lexicon_target lemon:language %s } "
            + "} ORDER BY ?lexicon_target ";

    public static final String GET_DIRECT_TRANSLATIONS_ONE_LANGUAGE_BABELNET = "PREFIX lemon: <http://www.lemon-model.net/lemon#> "
            + "PREFIX tr: <http://purl.org/net/translation#> "
            + "PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#> "
            + "SELECT DISTINCT ?written_rep_target ?POS ?lexicon_source ?lexicon_target ?babelnet "
            + "WHERE { "
            + "?form_source lemon:writtenRep %s . "
            + "?lex_entry_source lemon:lexicalForm ?form_source . "
            + "?sense_source lemon:isSenseOf  ?lex_entry_source .  "
            + "?lexicon_source lemon:entry ?lex_entry_source . "
            + "?lexicon_source lemon:language %s .  "
            + "?trans  tr:translationSense  ?sense_source .  "
            + "?trans  tr:translationSense  ?sense_target .  "
            + "?sense_target lemon:isSenseOf  ?lex_entry_target .   "
            + "?lex_entry_target lemon:lexicalForm ?form_target . "
            + "?form_target lemon:writtenRep ?written_rep_target . "
            + "?lex_entry_target  lexinfo:partOfSpeech ?POS .   "
            + "?lexicon_target lemon:entry ?lex_entry_target . "
            + "?lexicon_target lemon:language %s .  "
            + "minus { ?lexicon_target lemon:language %s } "
            + "optional {?sense_source lemon:reference ?babelnet "
            + "}} ORDER BY ?lexicon_target ";

    public static final String GET_DIRECT_TRANSLATIONS_ONE_LANGUAGE = "PREFIX lemon: <http://www.lemon-model.net/lemon#> "
            + "PREFIX tr: <http://purl.org/net/translation#> "
            + "PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#> "
            + "SELECT DISTINCT ?written_rep_target ?POS ?trans ?lexicon_source ?lexicon_target "
            + "WHERE { "
            + "?form_source lemon:writtenRep %s . "
            + "?lex_entry_source lemon:lexicalForm ?form_source . "
            + "?sense_source lemon:isSenseOf  ?lex_entry_source .  "
            + "?lexicon_source lemon:entry ?lex_entry_source . "
            + "?lexicon_source lemon:language %s .  "
            + "?trans  tr:translationSense  ?sense_source .  "
            + "?trans  tr:translationSense  ?sense_target .  "
            + "?sense_target lemon:isSenseOf  ?lex_entry_target .   "
            + "?lex_entry_target lemon:lexicalForm ?form_target . "
            + "?form_target lemon:writtenRep ?written_rep_target . "
            + "?lex_entry_target  lexinfo:partOfSpeech ?POS .   "
            + "?lexicon_target lemon:entry ?lex_entry_target . "
            + "?lexicon_target lemon:language %s .  "
            + "minus { ?lexicon_target lemon:language %s } "
            + "} ORDER BY ?lexicon_target ";

    public static final String GET_INDIRECT_TRANSLATIONS_ONE_LANGUAGE_BABELNET = "PREFIX lemon: <http://www.lemon-model.net/lemon#> "
            + "PREFIX tr: <http://purl.org/net/translation#> "
            + "PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#> "
            + "SELECT DISTINCT ?written_rep_pivot ?written_rep_target ?lexicon_source ?lexicon_target ?POS ?babelnet "
            + "WHERE { "
            + "?form_source lemon:writtenRep %s . "
            + "?lex_entry_source lemon:lexicalForm ?form_source . "
            + "?sense_source lemon:isSenseOf  ?lex_entry_source . "
            + "?lex_entry_source  lexinfo:partOfSpeech ?POS . "
            + "?lexicon_source lemon:entry ?lex_entry_source . "
            + "?trans  tr:translationSense  ?sense_source . "
            + "?trans  tr:translationSense  ?sense_pivot . "
            + "?sense_pivot lemon:isSenseOf  ?lex_entry_pivot . "
            + "?lex_entry_pivot lemon:lexicalForm ?form_pivot . "
            + "?form_pivot lemon:writtenRep ?written_rep_pivot . "
            + "?lexicon_pivot lemon:entry ?lex_entry_pivot . "
            + "?lexicon_pivot lemon:language ?lang_pivot. "
            + "?sense_pivot_target lemon:isSenseOf  ?lex_entry_pivot . "
            + "?indirect_trans  tr:translationSource  ?sense_pivot_target . "
            + "?indirect_trans  tr:translationTarget  ?sense_target . "
            + "?sense_target lemon:isSenseOf  ?lex_entry_target . "
            + "?lex_entry_target lemon:lexicalForm ?form_target . "
            + "?form_target lemon:writtenRep ?written_rep_target . "
            + "?lexicon_target lemon:entry ?lex_entry_target ; "
            + "lemon:language %s.  "
            + "filter (?lang_pivot != %s && ?lang_pivot != %s) "
            + "optional {?sense_pivot lemon:reference ?babelnet . ?sense_pivot_target lemon:reference ?babelnet . } "
            + "} order by ?lexicon_target";

    public static final String GET_INDIRECT_TRANSLATIONS_ONE_LANGUAGE = "PREFIX lemon: <http://www.lemon-model.net/lemon#> "
            + "PREFIX tr: <http://purl.org/net/translation#> "
            + "PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#> "
            + "SELECT DISTINCT ?written_rep_pivot ?written_rep_target ?lexicon_source ?lexicon_target ?POS "
            + "WHERE { "
            + "?form_source lemon:writtenRep %s . "
            + "?lex_entry_source lemon:lexicalForm ?form_source . "
            + "?sense_source lemon:isSenseOf  ?lex_entry_source . "
            + "?lex_entry_source  lexinfo:partOfSpeech ?POS . "
            + "?lexicon_source lemon:entry ?lex_entry_source . "
            + "?trans  tr:translationSense  ?sense_source . "
            + "?trans  tr:translationSense  ?sense_pivot . "
            + "?sense_pivot lemon:isSenseOf  ?lex_entry_pivot . "
            + "?lex_entry_pivot lemon:lexicalForm ?form_pivot . "
            + "?form_pivot lemon:writtenRep ?written_rep_pivot . "
            + "?lexicon_pivot lemon:entry ?lex_entry_pivot . "
            + "?lexicon_pivot lemon:language ?lang_pivot. "
            + "?sense_pivot_target lemon:isSenseOf  ?lex_entry_pivot . "
            + "?indirect_trans  tr:translationSource  ?sense_pivot_target . "
            + "?indirect_trans  tr:translationTarget  ?sense_target . "
            + "?sense_target lemon:isSenseOf  ?lex_entry_target . "
            + "?lex_entry_target lemon:lexicalForm ?form_target . "
            + "?form_target lemon:writtenRep ?written_rep_target . "
            + "?lexicon_target lemon:entry ?lex_entry_target ; "
            + "lemon:language %s.  "
            + "filter (?lang_pivot != %s && ?lang_pivot != %s) "
            + "} order by ?lexicon_target";
}
